/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LoadChart: typeof import('./src/components/LoadChart.vue')['default']
    LoadingCover: typeof import('./src/components/LoadingCover.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    NodeCard: typeof import('./src/components/NodeCard.vue')['default']
    NodeGeneralCards: typeof import('./src/components/NodeGeneralCards.vue')['default']
    PingChart: typeof import('./src/components/PingChart.vue')['default']
    Provider: typeof import('./src/components/Provider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
