shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
packages:
  - .
catalog:
  '@antfu/eslint-config': ^7.4.3
  '@iconify/json': ^2.2.442
  '@tsconfig/node24': ^24.0.4
  '@types/js-cookie': ^3.0.6
  '@types/node': ^24.10.13
  '@unocss/eslint-config': ^66.6.0
  '@unocss/eslint-plugin': ^66.6.0
  '@unocss/preset-icons': ^66.6.0
  '@unocss/preset-web-fonts': ^66.6.0
  '@unocss/preset-wind4': ^66.6.0
  '@unocss/transformer-directives': ^66.6.0
  '@unocss/transformer-variant-group': ^66.6.0
  '@vitejs/plugin-vue': ^6.0.4
  '@vue/eslint-config-typescript': ^14.6.0
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^14.2.1
  echarts: ^6.0.0
  eslint: ^9.39.2
  eslint-plugin-format: ^1.4.0
  eslint-plugin-oxlint: ~1.46.0
  eslint-plugin-vue: ~10.8.0
  jiti: ^2.6.1
  js-cookie: ^3.0.5
  naive-ui: ^2.43.2
  npm-run-all2: ^8.0.4
  oxlint: ~1.47.0
  pinia: ^3.0.4
  sass: ^1.97.3
  sass-embedded: ^1.97.3
  typescript: ~5.9.3
  unocss: ^66.6.0
  unplugin-auto-import: ^21.0.0
  unplugin-vue-components: ^31.0.0
  vite: ^7.3.1
  vite-plugin-static-copy: ^3.2.0
  vite-plugin-vue-devtools: ^8.0.6
  vue: ^3.5.28
  vue-echarts: ^8.0.1
  vue-router: ^5.0.2
  vue-tsc: ^3.2.4
packageExtensions: '[]'
